name: run-ansible-playbook

on: [ push ]

jobs:
  install-ansible-requirements-then-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - run: pip install -r requirements.txt
      - run: ansible-galaxy collection install ansible.posix community.docker community.general community.postgresql
      - run: ansible --version
      - run: ansible-community --version
      - run: ansible-playbook --version
      - run: ansible-galaxy --version
      #- run: cd ./src && ansible-playbook -i inventories/development.yml --vault-password-file ${HOME}/.ssh/vault_pass playbooks/setup-localhost.yml
      - run: cd ./src && ansible-playbook -i inventories/development.yml playbooks/setup-localhost.yml
        env:
          ANSIBLE_ROLES_PATH: "./roles/v0.1:./roles/v0.2:./roles/v0.3:./roles/v1.0"
